language: java

script: ./gradlew check
after_success: ./gradlew aggregatedJavadocs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: tjxibY5PwLxUSW3Pz23Zqw  # Set in travis-ci.org dashboard
  local_dir: build/docs
  on:
    branch: master
